version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
 
  backend:
    build: .
    command: bash -c "/startup.sh"
    volumes:
      - .:/src
      - ./scripts/startup.sh:/startup.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      # - SECRET_KEY=${SECRET_KEY}
      # - DB_HOST=${DB_HOST}
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
    depends_on:
      - db