# Generated by Django 4.1.7 on 2023-04-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('In-Progress', 'IP'), ('Completed', 'CP')], default='UD', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Comments')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='todo_task.task')),
            ],
        ),
    ]
